# SPDX-License-Identifier: AGPL-3.0-only
"""Semantic inventory consumed by coordinated algorithm activation."""

STRATEGY_POLICY = {
    "schema": "strategy-v1",
    "rules_revision": 1,
    "serializer": "compact-utf8-json-v1",
    "frame_bytes": 65536,
    "payload_bytes": 32768,
    "event_bytes": 65536,
    "header_bytes": 8192,
    "drivers": 64,
    "candidate_pairs": 126,
    "source_ring": 16,
    "trend_ring": 20,
    "emission_records": 2048,
    "situations": 16,
    "evidence": 512,
    "situation_evidence": 96,
    "cooldown_seconds": 60,
    "timing_age_seconds": 30,
    "timing_skew_seconds": 5,
    "pace_age_seconds": 300,
    "pace_completed_lap_lag": 2,
    "pace_event_threshold": 0.3,
    "pace_signature_bucket": 0.5,
    "pit_signature_bucket": 2,
    "pit_max_own_laps_ago": 20,
    "pit_cycle_seconds": 600,
    "pit_cycle_own_laps": 5,
    "close_pair_seconds": 3,
    "weather_age_seconds": 300,
    "weather_comparison_seconds": 900,
    "temperature_threshold": 2,
    "wind_speed_threshold": 2,
    "wind_direction_threshold": 30,
    "wind_direction_min_speed": 1,
    "closing_threshold": 0.15,
    "prominence_weights": [30, 15, 15, 10, 10, 10, 5, 5],
    "distance_producer": "unavailable",
    "pit_loss_transfer": "same_driver_green_no_rain_change",
}
